image: node:10

pipelines:
  default:
    - step:
        name: Installation
        caches:
          - node
        script:
          - npm install
        artifacts:
          - node_modules/**
          - package.json
    - step:
        name: Docker build
        services:
          - docker
        script:
          - myVersion=$(cat "/package.json" \
            | grep version \
            | head -1 \
            | awk -F:'{ print $2 }' \
            | sed 's/[",]//g' \
            | tr -d '[[:space:]]')
          - docker version
          - docker build -t dnaevolutions/jopt_demoapplication:${myVersion} .
          - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASS
          #- docker push dnaevolutions/jopt_demoapplication:latest
definitions:
  services:
    docker:
      memory: 2048
