image: node:10

pipelines:
  default:
    - step:
        name: Installation
        caches:
          - node
        script:
          - npm install
        artifacts:
          - node_modules/** # Save modules for next steps
    - step:
        name: Docker build
        script:
          - docker version
          - docker build -t dnaevolutions/jopt-demoapplication .
          - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASS
          - docker push dnaevolutions/jopt-demoapplication
