image: node:18.19.1

pipelines:
    tags:
      '*':
        - step:
            name: Installation
            caches:
              - node
            script:
              - npm install
              - npm run get-version --silent > ./VERSION
            artifacts:
              - node_modules/**
              - VERSION
        - step:
            name: Docker build
            services:
              - docker
            script:
              - myVersion=$(cat "VERSION")
              - docker version
              - docker build -t dnaevolutions/jopt_demoapplication:${myVersion} .
              - docker tag dnaevolutions/jopt_demoapplication:${myVersion} dnaevolutions/jopt_demoapplication:latest
              - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASS
              - docker push dnaevolutions/jopt_demoapplication:latest
              - docker push dnaevolutions/jopt_demoapplication:${myVersion}
definitions:
  services:
    docker:
      memory: 3072
